include(CheckIncludeFiles)
include(CheckFunctionExists)
include(CheckSymbolExists)

configure_file(${CMAKE_CURRENT_SOURCE_DIR}/autoconfig.in.h ${CMAKE_CURRENT_SOURCE_DIR}/include/autoconfig.h)

check_include_files("arpa/inet.h" HAVE_ARPA_INET_H)
check_include_files("dlfcn.h" HAVE_DLFCN_H)
check_include_files("fcntl.h" HAVE_FCNTL_H)
check_include_files("inttypes.h" HAVE_INTTYPES_H)
check_include_files("limits.h" HAVE_LIMITS_H)
check_include_files("memory.h" HAVE_MEMORY_H)
check_include_files("netdb.h" HAVE_NETDB_H)
check_include_files("netinet/in.h" HAVE_NETINET_IN_H)
check_include_files("pthread.h" HAVE_PTHREAD)
check_include_files("stdint.h" HAVE_STDINT_H)
check_include_files("stdlib.h" HAVE_STDLIB_H)
check_include_files("strings.h" HAVE_STRINGS_H)
check_include_files("string.h" HAVE_STRING_H)
check_include_files("string.h" HAVE_STRNDUP)
check_include_files("syslog.h" HAVE_SYSLOG_H)
check_include_files("sys/ioctl.h" HAVE_SYS_IOCTL_H)
check_include_files("sys/socket.h" HAVE_SYS_SOCKET_H)
check_include_files("winsock2.h" HAVE_WIN_SOCKET_H)
check_include_files("sys/stat.h" HAVE_SYS_STAT_H)
check_include_files("sys/time.h" HAVE_SYS_TIME_H)
check_include_files("sys/types.h" HAVE_SYS_TYPES_H)
check_include_files("unistd.h" HAVE_UNISTD_H)
check_include_files("ws2tcpip.h" HAVE_WS2TCPIP_H)


check_function_exists("fseeko;ftello" HAVE_FSEEKO)
check_function_exists("strndup" HAVE_STRNDUP)
check_function_exists("strnlen" HAVE_STRNLEN)
check_function_exists("vprintf" HAVE_VPRINTF)
check_function_exists("_doprnt" HAVE_DOPRNT)


check_symbol_exists("off_t" "sys/types.h" HAVE_OFF_T)
check_symbol_exists("size_t" "sys/types.h;stddef.h;cdefs.h;types.h" HAVE_SIZE_T)
check_symbol_exists("socklen_t" "sys/socket.h;winsock2.h;w32api/winsock2.h;ws2tcpip.h" HAVE_SOCKLEN_T)